import Head from "next/head";
import EditorNavbar from "./components/EditorNavbar.component";
import dynamic from "next/dynamic";
import EditorGuide from "./components/EditorGuide.component";

const EditorBody = dynamic(import("../../components/EditorBody.component"), {
  ssr: false,
});

export default function NewPostPage() {
  return (
    <>
      <Head>
        <title>Title - Medium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditorNavbar />

      <div>
        <div className="container mx-auto max-w-5xl px-5">
          <EditorBody />
        </div>
      </div>
      <EditorGuide />
    </>
  );
}
