import Head from "next/head";
import type { ReactElement } from "react";
import Layout from "../layout";

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Me - Medium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-20 md:pr-32">
        <div className="flex justify-between">
          <div className="text-4xl font-semibold">Minh Pham</div>
          <div>test</div>
        </div>
      </div>
    </>
  );
}
