import Head from "next/head";
import PostsNavbar from "./components/PostsNavbar.component";

export default function PostPage() {
  return (
    <>
      <Head>
        <title>Title - Medium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostsNavbar />
      <main>
        <div className="container mx-auto max-w-3xl px-5">
          <div className="mt-10 flex gap-1 text-sm font-light text-slate-500">
            <div className="self-center text-yellow-500">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="h-4 w-4"
              >
                <path d="M10.5 1.875a1.125 1.125 0 0 1 2.25 0v8.219c.517.162 1.02.382 1.5.659V3.375a1.125 1.125 0 0 1 2.25 0v10.937a4.505 4.505 0 0 0-3.25 2.373 8.963 8.963 0 0 1 4-.935A.75.75 0 0 0 18 15v-2.266a3.368 3.368 0 0 1 .988-2.37 1.125 1.125 0 0 1 1.591 1.59 1.118 1.118 0 0 0-.329.79v3.006h-.005a6 6 0 0 1-1.752 4.007l-1.736 1.736a6 6 0 0 1-4.242 1.757H10.5a7.5 7.5 0 0 1-7.5-7.5V6.375a1.125 1.125 0 0 1 2.25 0v5.519c.46-.452.965-.832 1.5-1.141V3.375a1.125 1.125 0 0 1 2.25 0v6.526c.495-.1.997-.151 1.5-.151V1.875Z" />
              </svg>
            </div>
            Members only story
          </div>
          <div className="mt-7">
            <h1 className="text-4xl font-bold">The Origins of Dune</h1>
            <p className="mt-2 text-xl text-slate-500">
              Before you watch part 2 of Dune, learn about the inspirations and
              origins of Frank Herbert’s classic SciFi novel
            </p>
          </div>
          <div className="mt-7">
            <div className="flex gap-8">
              <div className="relative h-12 w-12 rounded-full bg-black">
                <div className="absolute left-9 top-5 h-8 w-8 rounded-full border-2 border-white bg-slate-500"></div>
              </div>
              <div>
                <div>
                  Aspiring Reader · <a className="text-green-600">Follow</a>
                </div>
                <div className="text-sm font-light text-slate-500">
                  Published in{" "}
                  <a className="text-black hover:underline">Hooked on Books</a>
                </div>
                <div className="text-sm font-light text-slate-500">
                  10 min read · Feb 24, 2024
                </div>
              </div>
            </div>
          </div>
          <div className="mt-10 flex justify-between border-b border-t border-slate-200 py-3 text-sm font-light text-slate-500">
            <div className="flex justify-start gap-5">
              <div className="flex gap-1">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-4 w-4 self-center"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282m0 0h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c.472 0 .745.556.5.96a8.958 8.958 0 0 0-1.302 4.665c0 1.194.232 2.333.654 3.375Z"
                  />
                </svg>
                3.7K
              </div>
              <div className="flex gap-1">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-4 w-4 self-center"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 0 1-.923 1.785A5.969 5.969 0 0 0 6 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337Z"
                  />
                </svg>
                38
              </div>
            </div>
            <div className="flex justify-end gap-5 text-slate-400">
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
                  />
                </svg>
              </button>
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
                  />
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M15.91 11.672a.375.375 0 0 1 0 .656l-5.603 3.113a.375.375 0 0 1-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112Z"
                  />
                </svg>
              </button>
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div className="prose prose-xl container mx-auto mt-10 max-w-3xl px-5 font-serif">
          <figure>
            <img
              src="https://miro.medium.com/v2/resize:fit:2000/format:webp/0*FEP16gXObxcHgiVz.jpg"
              className="w-full"
            />
            <figcaption>
              Dune promotional picture from UHD Wallpapers
            </figcaption>
          </figure>
          <h2>Moral Uncertainty — What is the Good?</h2>
          <p>
            {" "}
            In 1953, a journalist by the name of Frank Herbert traveled to
            Florence, Oregon to write an article about the coastal dunes that
            had become a big tourist destination and a site of a long-standing
            environmental struggle.
          </p>
          <p>
            The Oregon Dunes span over 30,000 acres and still attract over a
            million and a half tourists to this day. But long before Herbert was
            a journalist and before environmental issues were everywhere in the
            news, the coastal communities in the 1920s were struggling with the
            impact and movement of these dunes.
          </p>
          <p>
            High coastal winds shifted the dunes constantly, swallowing roads,
            railroad tracks, homes, and more. To combat this constantly shifting
            landscape, the US Department of Agriculture planted European Beach
            Grass in hopes of stabilizing the dunes.
          </p>
          <p>
            Although the grass worked in some areas there simply wasn’t enough
            to cover the huge footprints of the dunes — the type you’d expect to
            see in African deserts.
          </p>
          <p>
            In the areas where the grass was working, a new problem arose: the
            grass itself was an invasive species and soon the area was overgrown
            and the landscape shifted.
          </p>
          <p>
            Over a few decades, parts of the dunes that were once used for
            sledding and recreation were covered in forest. The grass had not
            only stabilized some areas, but had allowed other plant life to
            grow.
          </p>
          <p>
            This struggle between man and nature — the effort to form something
            as wild as a landscape into a stable environment to build on — would
            be the foundation for Herbert’s debut novel, Dune.
          </p>
          <blockquote>
            “These waves can be every bit as devastating as a tidal wave in
            property damage.” - Frank Herbert
          </blockquote>{" "}
          <div className="blur-sm">
            This struggle between man and nature — the effort to form something
            as wild as a landscape into a stable environment to build on — would
            be the foundation for Herbert’s debut novel, Dune.
          </div>
          <div className="blur-sm">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae
            aperiam numquam voluptas dolorem sint provident est quae veniam,
            amet ab a rerum, adipisci quasi quis magni expedita? Laborum, omnis
            aperiam.
          </div>
        </div>
        <div className="mx-auto my-10 max-w-xl text-center">
          <div className="font-serif text-2xl">
            Create an account to read the full story.
          </div>
          <div className="mt-10 text-sm">
            <p>The author made this story available to Medium members only.</p>
            <p>
              If you’re new to Medium, create a new account to read this story
              on us.
            </p>
          </div>
          <div className="mx-auto mt-10 flex max-w-sm flex-col gap-3">
            <a className="relative rounded-full border border-black px-3 py-2">
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                className="absolute left-5"
              >
                <g fill-rule="evenodd" clip-rule="evenodd">
                  <path
                    d="M20.64 12.2c0-.63-.06-1.25-.16-1.84H12v3.49h4.84a4.14 4.14 0 0 1-1.8 2.71v2.26h2.92a8.78 8.78 0 0 0 2.68-6.61z"
                    fill="#4285F4"
                  ></path>
                  <path
                    d="M12 21a8.6 8.6 0 0 0 5.96-2.18l-2.91-2.26a5.41 5.41 0 0 1-8.09-2.85h-3v2.33A9 9 0 0 0 12 21z"
                    fill="#34A853"
                  ></path>
                  <path
                    d="M6.96 13.71a5.41 5.41 0 0 1 0-3.42V7.96h-3a9 9 0 0 0 0 8.08l3-2.33z"
                    fill="#FBBC05"
                  ></path>
                  <path
                    d="M12 6.58c1.32 0 2.5.45 3.44 1.35l2.58-2.58A9 9 0 0 0 3.96 7.96l3 2.33A5.36 5.36 0 0 1 12 6.6z"
                    fill="#EA4335"
                  ></path>
                </g>
              </svg>
              <span className="w-full">Sign up with Google</span>
            </a>
            <a className="relative rounded-full border border-black px-3 py-2">
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                className="absolute left-5"
              >
                <path
                  d="M22 12a10 10 0 1 0-11.56 9.88V14.9H7.9V12h2.54V9.8c0-2.5 1.5-3.9 3.77-3.9 1.1 0 2.24.2 2.24.2v2.46H15.2c-1.24 0-1.63.78-1.63 1.57V12h2.78l-.45 2.9h-2.33v6.98A10 10 0 0 0 22 12z"
                  fill="#1877F2"
                ></path>
                <path
                  d="M15.9 14.9l.44-2.9h-2.78v-1.87c0-.8.39-1.57 1.63-1.57h1.26V6.1s-1.14-.2-2.24-.2c-2.28 0-3.77 1.4-3.77 3.9V12H7.9v2.9h2.54v6.98a10.07 10.07 0 0 0 3.12 0V14.9h2.33z"
                  fill="#fff"
                ></path>
              </svg>
              Sign up with Facebook
            </a>
            <a className="relative rounded-full border border-black px-3 py-2">
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                className="absolute left-5"
              >
                <g stroke="#242424">
                  <rect x="3.5" y="5.5" width="17" height="13" rx="1"></rect>
                  <path d="M3.5 8l8.5 6 8.5-6" stroke-linecap="round"></path>
                </g>
              </svg>
              Sign up with Email
            </a>
          </div>
          <div className="mt-10">
            Already have an account? <a className="underline">Sign in</a>
          </div>
        </div>
        <div className="container mx-auto max-w-3xl px-5 my-20">
          <div className="flex justify-between py-3 text-sm font-light text-slate-500">
            <div className="flex justify-start gap-5">
              <div className="flex gap-1">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-4 w-4 self-center"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282m0 0h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c.472 0 .745.556.5.96a8.958 8.958 0 0 0-1.302 4.665c0 1.194.232 2.333.654 3.375Z"
                  />
                </svg>
                3.7K
              </div>
              <div className="flex gap-1">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-4 w-4 self-center"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 0 1-.923 1.785A5.969 5.969 0 0 0 6 21c1.282 0 2.47-.402 3.445-1.087.81.22 1.668.337 2.555.337Z"
                  />
                </svg>
                38
              </div>
            </div>
            <div className="flex justify-end gap-5 text-slate-400">
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
                  />
                </svg>
              </button>
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="h-5 w-5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div className="bg-slate-50">
        <div className="container mx-auto max-w-3xl px-5 h-96">
            
        </div>
        </div>
        <div className="bg-slate-50 border-t border-slate-200">
        <div className="container mx-auto max-w-3xl px-5">
        <div className="py-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-600">
            <a className="hover:underline">Help</a>
            <a className="hover:underline">Status</a>
            <a className="hover:underline">About</a>
            <a className="hover:underline">Careers</a>
            <a className="hover:underline">Blog</a>
            <a className="hover:underline">Privacy</a>
            <a className="hover:underline">Terms</a>
            <a className="hover:underline">Text to speech</a>
            <a className="hover:underline">Teams</a>
          </div>
        </div>
        </div>
      </main>
    </>
  );
}
