import { Tab } from "@headlessui/react";
import Head from "next/head";
import { Fragment } from "react";
import { BottomNavigationItems } from "../components/BottomNavigationItems";
import Link from "next/link";
import Navbar from "../components/Navbar.component";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { getServerAuthSession } from "@/server/auth";
import { Session } from "next-auth";
import { useSessionContext } from "../contexts/Session.context";

export default function MePage() {
  const tabs = ["Home", "About"];
  const { session } = useSessionContext()
  return (
    <>
      <Head>
        <title>Me - Medium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col">
        <Navbar />
        <div className="container mx-auto grid h-full max-w-6xl flex-1 grid-cols-12 px-12 md:px-5">
          <div className="col-span-12 h-full md:col-span-8 md:pr-28">
            {session && (
              <>
                <div className="pt-20">
                  <div className="flex justify-between">
                    <div className="text-4xl font-semibold">{session.user.name}</div>
                    <div className="self-center">
                      <button>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="h-6 w-6"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
                          />
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
                <div className="mt-5">
                  <Tab.Group>
                    <Tab.List className="border-b border-gray-200 text-sm">
                      {tabs.map((item) => (
                        <Tab key={item} as={Fragment}>
                          {({ selected }: { selected: boolean }) => (
                            /* Use the `selected` state to conditionally style the selected tab. */
                            <button
                              className={`mr-6 py-5 outline-none ${selected && "border-b border-black opacity-100"}`}
                            >
                              {item}
                            </button>
                          )}
                        </Tab>
                      ))}
                    </Tab.List>
                    <Tab.Panels className="mt-10">
                      <Tab.Panel>
                        <div className="w-full"></div>
                      </Tab.Panel>
                      <Tab.Panel>
                        <div className="border-b border-gray-200 pb-10">
                          <div className="flex justify-center bg-gray-100/50 p-20">
                            <div className="center flex flex-col gap-5 text-center">
                              <div className="text-sm font-semibold">
                                Tell the world about yourself
                              </div>
                              <div className="px-5 text-xs">
                                Here’s where you can share more about yourself:
                                your history, work experience, accomplishments,
                                interests, dreams, and more. You can even add
                                images and use rich text to personalize your
                                bio.
                              </div>
                              <div>
                                <button className="mt-1 rounded-3xl border border-black px-4 py-2 text-sm">
                                  Get started
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="py-10">
                          <button className="text-sm text-green-600 hover:text-green-700">
                            1 following
                          </button>
                        </div>
                      </Tab.Panel>
                    </Tab.Panels>
                  </Tab.Group>
                </div>
              </>
            )}
          </div>
          <div className="hidden border-l border-gray-200 md:col-span-4 md:flex">
            <div className="flex h-full flex-col">
              <div className="flex-1">
                { session && <div className="ml-10 mt-20">
                  <img className="h-20 w-20 rounded-full" src={session.user.image || ""} />
                  <div className="mt-5 font-semibold">Minh Pham</div>
                  <div className="mt-6 text-xs text-green-600 hover:text-green-700">
                    Edit profile
                  </div>
                </div>}
              </div>
              <div className="flex flex-wrap gap-x-2 gap-y-1 px-5 py-5 text-xs text-gray-500">
                {BottomNavigationItems.map(({ href, name }) => (
                  <Link key={name} href={href} className="hover:underline">
                    {name}
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
